server:
  port: 8020

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yut520/base-cloud/
          search-paths: config-repo
          username:
          password: