server:
  port: 8020

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yut520/base-cloud/config-repo.git
          default-label: ${spring.profiles.active}